### ISSUE TITLE
Feature request: Add support for port associated delegate components and other enhancements

### ISSUE THREAD

**Issue by Jackneill** [cneben/QuickQanava#21]
I am trying to copy this look: 
![blender](http://answers.unity3d.com/storage/temp/27622-unityforum2.jpg)

 - As you can see, each port has an associated "qml component" with it. (Now only the graph has a port delegate.)

- I'd like to create node ports dynamically with custom and different delegates (as you can see in the pic). And this being not only visual but each port having a `value` QVariant property that can be read (and modified from within node/port).

- A model for ports (getting the label, dock type, value..)

- Also it would be nice to being able to connect ports without needing to click on the port and drag the connector, and just drag from the port (less of a pain).

- Expose the selection rectangle instead of {color,weight,margin} for better configurability (like radius etc.)

**Comment by cneben** [comment]
Good news: I have the exact same requirements (modelling OpenCV and Dlib @davisking process in a flow graph)

_• As you can see, each port has an associated "qml component" with it. (Now only the graph has a port delegate.)_

Well, actually the port delegate is global because it fit the need of 90% of users. However, a ‘portDelegate’ argument could easily be added to qan::Graph::insertInPort() method. QuickQanava doesn’t really care the concrete type of ports items as soon as it inherit from qan::PortItem, you can have a dock on the same node with different concrete types of ports, it’s not a problem: the dock layout code will handle it without troubles.

I will update the customdocks sample to demonstrate that.

_• I'd like to create node ports dynamically with custom and different delegates (as you can see in the pic). And this being not only visual but each port having a value QVariant property that can be read (and modified from within node/port)._

Not a problem: create a custom c++ port item with a value property inheriting from qan::PortItem and generate a custom delegate for it: Dock.qml is very simple (BTW, it should be modified using state and PropertyChanges just as you did for docks…), you just have to react to ‘dockType’ changes (only if you actually need labels).

I really don’t want to manage value modifications propagations as in @placeholder NodeEditor, because every dataflow solution has specific needs. You can easily react to topological modifications of graph using qan::Graph::installBehaviour() and bind to your valueChanged() signal to propagate changes… Behaviors are not described in the documentation, but I use them on a daily basis, it quite solid.

_• A model for ports (getting the label, dock type, value..)_

I will add topology/port mapping in the next commits: I want a simple interface for mapping an edge (either in/out) to a “port index”. Once you can do that mapping, it’s quite simple to get the port item (with already existing label/dockType properties) using edge->getSourceItem() or getDestinationItem(): it will return a qan::PortItem…

_• Also it would be nice to being able to connect ports without needing to click on the port and drag the connector, and just drag from the port (less of a pain)._

It would be great (I also need that feature), but I think the implementation is quite complex. Perhaps the most simple solution would be to add a signal draggedOver(qan::NodeItem* targetNode) in qan::PortItem and react accordingly exactly as in qan::Connector::connectorReleased(): keep in mind that port item are in fact … node item ! Port item are not draggable, but it would be easy to enable it (see setDraggable(false) in port item ctor) and create an edge when they are released over a target node…

BTW, I have no time to draft it for now, perhaps next month… PR welcome !

_•	Expose the selection rectangle instead of {color,weight,margin} for better configurability (like radius etc.)_

Node item has a ‘selectionItem’ property: you can just set nodeItem.selectionItem.radius to customize radius. The selection item is built when the node is selected in qan::Graph::addToSelectionImpl<>(), the selection item factory is qan::Graph::createRectangle(). Method name choice is very unfortunate: it should be createSelectionItem() and it should be virtual and overridable by the user. You can also expose ‘_rectangleComponent’ as a ‘selectionItemDelegate’ property and use delegates to generate selection item with … your custom items !

I will try to write the documentation for port/docks and polish the API: insertInPort() and insertOut() will be merged in a unique insertPort() method, IN/OUT is just a matter of manual configuration.

**Comment by Jackneill** [comment]
I'd like to implement a writable port model for nodes: be able to modify a nodes' ports (/remove them).
I was thinking about exposing `qanNode.h`'s _{in,out}Ports (as models eg. `using Ports = qcm::ContainerModel<QList, qan::PortItem *>;` ?) (though i read that you want to redesign qcm since QAbstractItemModel inheritence is heavy, but for now its used everywhere (but at least using QAbstractItemModel/QAbstractListModel is easy and idiomatic)). Please tell me if you had something different in mind.

**Comment by cneben** [comment]
qcm::ContainerModel will keep almost the same interface and continue inheriting QAbstractItemModel. I just plan to remove `_displayRoleProperty` and `itemCount` properties until the user really need these values (ie access them through `listReference` property). Such an interface change is easy to refactor across the framework, you shouldn't worry too much about this. (Btw, there is still no support for Std containers in "QuickContainers" and the whole lib need a lot of polishing...).

Adding observable models for in/out ports is a very good idea:

- I would rather put such a cache in qan::NodeItem since it make more sense to use it from a node delegate (for example to use a listview with custom delegates to show information extracted from port item)

- `_inPorts` and `_outPorts` in `qan::Node` are no longer used, I forgot to remove them, they are never initialized from `qan::Graph:: insertInPort()`

- I no longer want to make a distinction between in/out port, a port already has a type, so it might be in/out/in&out, there are no good reasons to have a dedicated API for that. `qan::Graph::insertInPort()` has to be renamed to `insertPort()` with and optional port type argument (insertOutPort() is empty and should be removed).

- `insertPort()` could then add any new port in `qan::NodeItem::_ports` port cache made with qcm::ContainerModel<QVector, qan::PortItem>. Container model will take care of watching for destruction of port items, so updating when an eventual qan::Graph::removePort() method is called is not even necessary.

- I think such a `ports` property (look at the implementation of `qan::Graph::selectedNodes` property it’s very similar) should be constant/read-only, my intention is to keep all topology management at graph level to simplify a “proxy pattern” on qan::Graph (for example to add undo/redo or modification management for serialization, a lot of my CS code rely on that).

Probably, we should create a new sample similar to NodeEditor calculator to have a convenient testbed for selecting ports, removing them with some sort of context menu and demonstrate the use of qan::GraphBehaviour we have already talked about…

Your PR are always welcome ;)

**Comment by cneben** [comment]
WIP dataflow sample...

![image](https://user-images.githubusercontent.com/13402251/33918082-d2b8ee74-dfb1-11e7-918c-ed78f04ce762.png)

**Comment by cneben** [comment]
WIP dataflow sample...

![image](https://user-images.githubusercontent.com/13402251/33953681-1a25f9f8-e036-11e7-86ee-1f2898e0f4da.png)

**Comment by Jackneill** [comment]
I'd like to implement a `void Graph::autoPositionNodes() noexcept` that would position the nodes. (Like when you load from a format that has no position coords for the nodes). I'm looking at boost's BPL (http://www.boost.org/doc/libs/1_66_0/libs/graph/doc/index.html) for it.
Are you okay with a dep on it? Or shall i make it optional? (Like if the header is available at compile-time (its a header-only lib))

**Comment by cneben** [comment]
No problem for me, but please add a "commentable" DEFINES+=HAVE_BOOST_BGL in quickqanava.pri.

I'am actually moving the build/configuration system from qmake to cmake (qmake will still be maintained), so it should be easy to configure it automatically in the near future.

Boost BGL is really a nightmare to work with (that's why I end up creating GTPO, I was initially planning to manage topology with BOOST). Probably a simple implementation of Kamada-Kawai would be easier to come with than building a topology adapter for BGL.

The main problem with auto layout out for me is to do it asynchronously in an efficient way while still allowing user interaction with the graph. If you just want to block until your algorithm has generated initial positions, probably the Qt elasticnodes sample force directed algorithm would be enought!

(thanks for your last contrib)
