### ISSUE TITLE
Adding undo/redo on graph editing would be nice!

### ISSUE THREAD

**Issue by shpshp** [cneben/QuickQanava#36]
Adding undo/redo on graph editing would be nice!

**Comment by cneben** [comment]
Undo/redo should be handled at user application level: Either in redux style (but GTpo still not has a very good support for invariance) or via a proxy on top of qan::Graph where you record user actions (add node, move node and so on). I won't add such a feature to the topology sample since it is just a showcase for basic features and it should remain simple. I might write an article about undo/redo in documentation one day or another...
